name: Azure Template Validation 
on: 
#  workflow_dispatch:
    push:
        branches:
            - main
permissions: 
  contents: read 
  id-token: write 
  pull-requests: write 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/App/requirements.txt
          pip install flake8  # Ensure flake8 is installed explicitly
      
      - name: Run flake8 and pylint
        run: |
          flake8 --config=.flake8 src/App/backend  # Specify the directory to lint